import { describe, expect, it } from 'vitest';
import {
  type AnswerStatus,
  type Confidence,
  LEGAL_STATUS_CONFIDENCE,
  isLegalStatusConfidence,
} from './answer-contract';
import { answerSchema, validateAnswerSchema } from './validate-schema';
import { appendAnswerVersion } from './versioning';
import { answerForStatus, answeredFixture, chartFixture } from './test-fixtures';

const STATUSES: AnswerStatus[] = [
  'Answered',
  'Partial',
  'NeedsClarification',
  'BlockedByPolicy',
  'NoReliableAnswer',
];
const CONFIDENCES: Confidence[] = ['High', 'Medium', 'Low', 'CannotDetermine'];

// Loosely-typed view of the committed schema for structural assertions.
const schema = answerSchema as unknown as {
  properties: { status: { enum: string[] }; confidence: { enum: string[] } };
  allOf: Array<{ oneOf?: unknown[] }>;
};

/**
 * C1 — schema-sync (no drift between answer-contract.ts and the JSON Schema).
 * The Status × Confidence legality is the drift-prone part of the contract, so
 * we generate the schema's legality `oneOf` from the TS source of truth
 * (LEGAL_STATUS_CONFIDENCE) and assert the committed schema matches exactly.
 * (The committed schema is intentionally richer than any TS→schema generator
 * output — it encodes cross-field legality via oneOf/if-then — so a full
 * generate-and-equal check would weaken it; this targets the part that matters.)
 */
describe('C1 schema-sync', () => {
  it('schema status/confidence enums match the TS legality table', () => {
    expect(new Set(schema.properties.status.enum)).toEqual(
      new Set(Object.keys(LEGAL_STATUS_CONFIDENCE)),
    );
    const allConfidences = new Set(Object.values(LEGAL_STATUS_CONFIDENCE).flat());
    expect(new Set(schema.properties.confidence.enum)).toEqual(allConfidences);
  });

  it('schema legality oneOf is generated by the TS legality table', () => {
    const expectedOneOf = (Object.keys(LEGAL_STATUS_CONFIDENCE) as AnswerStatus[]).map((status) => {
      const confs = LEGAL_STATUS_CONFIDENCE[status];
      return {
        properties: {
          status: { const: status },
          confidence: confs.length === 1 ? { const: confs[0] } : { enum: [...confs] },
        },
      };
    });
    const legalityBlock = schema.allOf.find((b) => Array.isArray(b.oneOf));
    expect(legalityBlock?.oneOf).toEqual(expectedOneOf);
  });
});

/**
 * C2 — legality: isLegalStatusConfidence() and the JSON Schema agree for all 20
 * Status × Confidence combinations.
 */
describe('C2 legality (20 combinations)', () => {
  for (const status of STATUSES) {
    for (const confidence of CONFIDENCES) {
      const legal = isLegalStatusConfidence(status, confidence);
      it(`${status} + ${confidence} -> ${legal ? 'legal' : 'illegal'} (TS == schema)`, () => {
        const { valid } = validateAnswerSchema(answerForStatus(status, confidence));
        expect(valid).toBe(legal);
      });
    }
  }
});

/**
 * C3 — unblock-required: a non-Answered Answer with no `unblock` fails both
 * validateAnswer and schema validation.
 */
describe('C3 unblock-required', () => {
  it('Partial without unblock fails validateAnswer and schema', async () => {
    const { validateAnswer } = await import('./answer-contract');
    const a = answeredFixture();
    a.status = 'Partial';
    a.confidence = 'Medium';
    // no unblock set
    const violations = validateAnswer(a);
    expect(violations.map((v) => v.code)).toContain('missing_unblock_on_non_answer');
    expect(validateAnswerSchema(a).valid).toBe(false);
  });
});

/**
 * C4 — answered-findings: status Answered with 0 keyFindings fails validateAnswer
 * (and schema).
 */
describe('C4 answered-findings', () => {
  it('Answered with no keyFindings fails validateAnswer and schema', async () => {
    const { validateAnswer } = await import('./answer-contract');
    const a = answeredFixture();
    a.keyFindings = [];
    const violations = validateAnswer(a);
    expect(violations.map((v) => v.code)).toContain('answered_without_findings');
    expect(validateAnswerSchema(a).valid).toBe(false);
  });
});

/**
 * C6 — charts are optional and backward-compatible: an Answer with no `charts`
 * stays valid, a well-formed `charts` array validates, and a malformed chart spec
 * (missing the required `points` series) is rejected by the schema.
 */
describe('C6 charts (optional, schema-validated)', () => {
  it('an Answered answer without charts is still schema-valid', () => {
    const a = answeredFixture();
    expect(a.charts).toBeUndefined();
    expect(validateAnswerSchema(a).valid).toBe(true);
  });

  it('a well-formed chart spec validates', () => {
    const a = answeredFixture();
    a.charts = [chartFixture('C1', 'E1')];
    expect(validateAnswerSchema(a).valid).toBe(true);
  });

  it('a chart whose spec has no points fails the schema', () => {
    const a = answeredFixture();
    const bad = chartFixture('C1', 'E1');
    // Simulate a malformed producer payload: empty series violates minItems.
    (bad.spec as { points: unknown[] }).points = [];
    a.charts = [bad];
    expect(validateAnswerSchema(a).valid).toBe(false);
  });
});

/**
 * C5 — versioning: a follow-up increments version, sets createdAfter, flips
 * isLatest; prior versions remain retrievable (no overwrite).
 */
describe('C5 versioning', () => {
  it('appendAnswerVersion increments version and preserves prior', () => {
    const v1 = answeredFixture();
    const v2draft = answeredFixture();
    v2draft.directAnswer = 'Broken down by day, the Summer Sale peaked on the 14th.';

    const answers = appendAnswerVersion([v1], v2draft, {
      createdAt: '2026-06-17T01:00:00.000Z',
      trigger: 'followup',
      fromVersion: 1,
    });

    expect(answers).toHaveLength(2);
    const [prev, latest] = answers;
    // prior version preserved and retrievable, just demoted
    expect(prev?.meta.version).toBe(1);
    expect(prev?.meta.isLatest).toBe(false);
    expect(prev?.directAnswer).toBe(v1.directAnswer);
    // new version
    expect(latest?.meta.version).toBe(2);
    expect(latest?.meta.isLatest).toBe(true);
    expect(latest?.meta.createdAfter).toEqual({ kind: 'followup', fromVersion: 1 });
    expect(latest?.directAnswer).toBe(v2draft.directAnswer);
  });
});
